### ISSUE TITLE
FE15 Events 

### ISSUE THREAD

**Issue by RavenSWFS** [thane98/paragon#105]
Hey, I've been facing an issue while editing Events code directly in Paragon.

It may happen to be a translation issue, but whenever I apply even the smallest change, it removes the first and last letter of some variables, making the script completely unusable, Like so : 
![image](https://github.com/thane98/paragon/assets/163743016/7aaa4fdc-3df3-44f3-84ec-033c8240ab40)

Thanks for reading, and hope you eventually find a fix.

Fyi, I'm using an USA Special Edition rom for everything I do on Paragon with FE SOV.

**Comment by thane98** [comment]
I've reverted this editor to the previous UI for the time being while I look into this.

**Comment by RavenSWFS** [comment]
Thanks a lot !
