### ISSUE TITLE
FE15 - Attempting to add support bonuses to characters recieves an error

### ISSUE THREAD

**Issue by ilikepizza107** [thane98/paragon#106]
Hello, I've recently added two units to the game, but when I attempt to give them support bonuses in the "Supports" section in "Characters", I get this error:

(Before the error, I click "OK" here)
![image](https://github.com/thane98/paragon/assets/90655367/a6f7ee3c-7c05-47e8-8d89-c9cb7d75904c)

(After clicking "OK")
![image](https://github.com/thane98/paragon/assets/90655367/31e4e7f7-292a-44ae-97fd-b10ce6e4c801)

Log window:
![image](https://github.com/thane98/paragon/assets/90655367/043f6634-856e-426c-a8d8-46d0181cd297)

**Comment by ilikepizza107** [comment]
I want to add that this happens even without custom characters in the equation: here's me trying to do it with Alm here
![image](https://github.com/thane98/paragon/assets/90655367/f490d093-12ed-48ec-b120-a81a700cd083)
![image](https://github.com/thane98/paragon/assets/90655367/6c9dbd89-7ba6-42b7-ada6-72a640014e03)

**Comment by RavenSWFS** [comment]
Been facing the same issue here.

**Comment by RavenSWFS** [comment]
Found a way to fix it. You cannot create the entire supports through the character tab, you must make it via these :
![image](https://github.com/user-attachments/assets/e89d7663-c930-4d4e-b2f7-672b5182b072)
And then it automatically creates the supports, and you'll just have to add the dialogues.

**Comment by thane98** [comment]
This should be fixed by https://github.com/thane98/paragon/releases/tag/Rewrite-Alpha-2-3-3
