### ISSUE TITLE
No paragon.json file in download

### ISSUE THREAD

**Issue by SirFunkalo** [thane98/paragon#109]
I downloaded the newest version of Paragon and got the following error message: 

ERROR:root:Failed to load config paragon.json.
Traceback (most recent call last):
  File "paragon\model\configuration.py", line 31, in load
FileNotFoundError: [Errno 2] No such file or directory: 'paragon.json'

**Comment by thane98** [comment]
This is expected when starting Paragon for the first time.

**Comment by SirFunkalo** [comment]
I seem to have this problem every time I start it. How does the json file generate? My apologies if this is a stupid question. Googling has not revealed the answer to me.On Sep 21, 2024, at 8:36 AM, thane98 ***@***.***> wrote:﻿
This is expected when starting Paragon for the first time.

**Comment by thane98** [comment]
This file is usually generated automatically the first you close Paragon. If it's not being created, it's possible that Paragon doesn't have permission to write to wherever you're running it from.

I'll attach the default file here in case you want to add it manually.

[paragon.json](https://github.com/user-attachments/files/17085778/paragon.json)

**Comment by SirFunkalo** [comment]
Thank you! Closing Paragon fixed that particular problem, but I am not
being told there is not asset/ROM0.lz. I'm not sure if I put the wrong romf
directory, but I looked for the folder with the bin.lz files. Do you know
what caused this error?

**Comment by thane98** [comment]
The error message should list what paths it's using to look for the file.

For reference, the extracted RomFS directory should look like this:
![Screenshot 2024-09-24 070353](https://github.com/user-attachments/assets/db2e02a8-333b-44d8-bd7e-81b1f2aae64a)

**Comment by SirFunkalo** [comment]
Thank you for the reference, and for your patience! Everything is working as intended now. I really do appreciate your help.On Sep 24, 2024, at 7:05 AM, thane98 ***@***.***> wrote:﻿
The error message should list what paths it's using to look for the file.
For reference, the extracted RomFS directory should look like this:
Screenshot.2024-09-24.070353.png (view on web)
