### ISSUE TITLE
MacOS "Bad CPU in executable" error

### ISSUE THREAD

**Issue by ImAMerc** [thane98/paragon#110]
Alpha rewrite 2-3-1 won't open, and my terminal is producing a bad CPU type in executable error.

I have an Intel Mac with an i9 processor, if that helps

**Comment by thane98** [comment]
The Mac builds of Paragon are done through GitHub because I don't own a Mac. I suspect that these builds are now done on silicon Macs which use arm.

I'm going to put out a small update with some fixes later today. I'll see if I can do separate builds for arm and x86 as part of it.

**Comment by ImAMerc** [comment]
Thanks much, Thane.  Can't wait to get back to using the program

**Comment by thane98** [comment]
No problem. This release has a separate build for x86: https://github.com/thane98/paragon/releases/tag/Rewrite-Alpha-2-3-2
