### ISSUE TITLE
New Project Loading Error

### ISSUE THREAD

**Issue by raidxnnn** [thane98/paragon#111]
Traceback (most recent call last):
  File "paragon\core\workers\load_project_worker.py", line 72, in run
Exception: Failed to load text data definitions.

Caused by:
    0: Failed to read text definitions from path 'C:\Users\16198\AppData\Local\Temp\Rar$EXa27004.22408\Data\FE14\Text.yml'
    1: The system cannot find the path specified. (os error 3)

I was able to successfully make one project in FE13, but am now getting this error every time i try to make more projects in FE13 and with trying to set up projects for FE14

**Comment by thane98** [comment]
The path it's looking in is kind of odd. Paragon expects to find the `Data` folder in the same directory the exe is run from - are you running Paragon through a shortcut or something similar?

**Comment by raidxnnn** [comment]
I've been running Paragon.exe just through the zip file, should i unzip it and put it somewhere instead??

**Comment by thane98** [comment]
Yes, I recommend unzipping it first.
