### ISSUE TITLE
FE14-Script Editor doesn't have "new file"

### ISSUE THREAD

**Issue by RottedFish** [thane98/paragon#114]
Unlike the standalone release of Exalt, the script editor in Paragon doesn't have an option to make a new file. Hoping this gets added for ease of use.

**Comment by thane98** [comment]
![Screenshot 2024-11-28 085317](https://github.com/user-attachments/assets/7d9dd580-6d08-4c37-a7c7-39363deba5a9)
There isn't a button on the UI, but you should have an option to add new scripts if you right click any directory besides "Standard Library".

I can add buttons for this to make it more intuitive.
