### ISSUE TITLE
Add a [Copy selected unit] Button to the chapter editor.

### ISSUE THREAD

**Issue by dawnbomb** [thane98/paragon#31]
It's all in the title, rather then being a shortcut (then remove the shortcut so people don't accidentally do it)

Or maybe just have a options menu to turn on / off shortcuts...

**Comment by thane98** [comment]
I would like to add a toolbar with buttons for adding, removing, and copying units and factions in the chapter editor remake. If I take this approach, I'll probably add a context menu for these actions as well.
