### ISSUE TITLE
Chapter editor: Sprites, or Symbols.

### ISSUE THREAD

**Issue by dawnbomb** [thane98/paragon#37]
In the chapter editor, it would be nice to have enemy sprites appear in the editor. I assume this isn't done for some reason either because getting them is a bunch of effort, or it creates some problem with how paragon is structured right now. But reguardless, if it can't be done, there is a ok alternative.

we can be able to apply a letter to unit circles (only in paragon). For example, a user can create a enemy Hayato in birthright, and assign the letter H to him. The letter would appear inside his unit circle on the map (H) in the editor, but not ingame. This would help modders keep track of things better. It's not as good as sprites showing in the editor, but if that can't happen, it's an alright next best thing.

**Comment by thane98** [comment]
The BCH parsing code used by the conversation editor should also support reading sprites. There are some additional things to deal with here since the process for assembling sprites is a little complicated, but this is a planned feature for the chapter editor remake.
