### ISSUE TITLE
Paragon Options Menu

### ISSUE THREAD

**Issue by dawnbomb** [thane98/paragon#38]
I will update this as i think of things to add. but for now.

Suggestion 1: [Full Item list Or Item Category List]
Currently in chapter editor for a unit, the item list is...fucking huge. absolutely massive, you have to scroll for a significant time to go up / down the list. I sugest a alternate mode where you can click item 1, click category, then click a item. Caregories being the following.
Swords, Katanas, Spears, Naginatas,  Axes, Maces, Bows, Yumis, Daggers, Shurikens, Tomes, Scrolls,  Other, Staffs, Items, and Custom. Custom being any items after the games default item list.

**Comment by thane98** [comment]
I'm not opposed to the idea, but I'm not sure what this would look like in terms of UI. Do you have a picture or example of how what this setup would look like?

Alternatively, adding a search bar to the drop down might address the issue. Any thoughts on that approach?
