### ISSUE TITLE
Gender not recognized in dialogue editor

### ISSUE THREAD

**Issue by singlypringle** [thane98/paragon#45]
The command:
`$GHe,She|`
Normally should print He for male Corrin and She for female Corrin. However, it is not recognized. This error is shown instead.
`Unknown command $Ghe`

**Comment by thane98** [comment]
The command has a slightly different syntax in Paragon. For your example, you would use: `$G(He,She)`

For more information, see the [command reference](https://github.com/thane98/paragon/wiki/Conversation-Editor).

**Comment by singlypringle** [comment]
I feel so dumb that I never saw the wiki earlier haha. Thank you so much, this helps a lot. Honestly this tool is so insanely awesome and powerful thank you so much
