### ISSUE TITLE
"PlayMusic" command doesn't work for supports

### ISSUE THREAD

**Issue by singlypringle** [thane98/paragon#46]
Using "PlayMusic" at the beginning of a support doesn't play the music. I had to manually edit the support file to add it. No idea if this is intentional or not, but I thought I'd mention it.

**Comment by thane98** [comment]
Music in supports can be a fragile since the game also tries to assign music in a different location.

That said, I was able to get music to play in custom supports by assigning the music at the end of the "setup" portion (after setting up portraits, emotions, etc).

Is Paragon not adding the music command to the file, or is the music just not playing like you expect it to?

**Comment by singlypringle** [comment]
Can you send me an example of a support file? I'm running into a lot of issues: the music isn't playing, blank textboxes, etc. I'm following as closely as possible the existing support files in the unedited RomFS but for some reason it doesn't work in my game the same way. It looks perfectly fine in the preview, but not in-game.

**Comment by thane98** [comment]
Sorry for not getting back on this sooner. Here's a small example which I've confirmed plays correctly in game (including the music):
```
$ConversationType 1
$NewSpeaker Hinoka
$Reposition 3
$NewSpeaker Hinoka 2
$Reposition 7
$Wait 0
$SetSpeaker Hinoka
$Emotions(Standard,)
$PlayMusic(STRM_EVT_GAG_E1,0)
So let me get this straight...
$Await

$Clear
You have strictly higher bases...
$Await

$Clear
And higher growths...
$Await

$Clear
$Emotions(Suffering,)
And the "Always Crit" flag.
$AwaitAndClear

$SetSpeaker Hinoka 2
$Emotions(Standard,)
Sounds about right.
$AwaitAndClear

$SetSpeaker Hinoka
$Panicked
$Emotions(Suffering,)
How is that fair!?!
$AwaitAndClear

$SetSpeaker Hinoka 2
$Emotions(Standard,)
What part of "the superior Hinoka"
did you not understand?
$Await
```
If things aren't rendering correctly, you can use `$Emotions`. This command has some extra effects which help synchronize the renderer with the commands you entered.
