### ISSUE TITLE
Can't edit the text in the Chapter module Text editor.

### ISSUE THREAD

**Issue by Biffaloe** [thane98/paragon#48]
Any changes I make in the text editor of the Chapter module is immediately reverted on changing tabs even when using the text editor or the main paragon save buttons.

**Comment by thane98** [comment]
In the text editor, your changes are not written back unless you save / preview since there might be errors in your script.

Did you save / preview first?

**Comment by Biffaloe** [comment]
Yup, I even tried saving in the main the project as well, but as soon as I change tabs the changes revert back to the original script

**Comment by thane98** [comment]
After doing some more testing, I was able to reproduce this on alpha 14-2. I'll try have this fixed before the next release.

**Comment by thane98** [comment]
Resolved with [09f8969](https://github.com/thane98/paragon/commit/09f89696a38bfe99274763a02deaac27688e891a).
