### ISSUE TITLE
Dispos Won't Save

### ISSUE THREAD

**Issue by princessblucy** [thane98/paragon#49]
[paragon.log](https://github.com/thane98/paragon/files/4944944/paragon.log)
The dispos file wouldn't save and the only thing that I found was odd was the double forward slash on the file path.
It was with C010 for the record.

**Comment by thane98** [comment]
Thank you for reporting this. It looks like this was an issue with translating between signed and unsigned when displaying coordinates in the map editor.

I've fixed this with commit [15cb337](https://github.com/thane98/paragon/commit/15cb3375069592056bd68a4943d19441087eb309).
