### ISSUE TITLE
[enhancement] Longer width/stretching for text boxes in the FE14 Character Editor's Dialogue tab

### ISSUE THREAD

**Issue by KSR480** [thane98/paragon#69]
I've been trying to locate these text boxes in the ui folder but I could barely find anything to edit, I hope it's not some preset that needs to be replaced universally in a complicated way.
Reason is that I cannot be productive reviewing Dialogue in the Character Editor en masse with a textbox this small.

**Comment by thane98** [comment]
Paragon's currently going through a rewrite, so it may be a few weeks before a release for this is out. It should be a quick fix though.

Also, this issue *may* be specific to Mac if that's what you're using. On Windows, these boxes stretch with the window.

**Comment by KSR480** [comment]
I am indeed using macOS, 10.14.6 for what it's worth.
Thank you for the quick reply!
