### ISSUE TITLE
Toggling voiced lines in the FE14 Character Data Dialogue tab

### ISSUE THREAD

**Issue by KSR480** [thane98/paragon#70]
I manually removed the (Voice) paragraphs from the FE14Dialogue.json and this happened; it'd be nice to have an official toggle still

> ERROR:root:A critical error occurred while initializing main
> Traceback (most recent call last):
>   File "/Users/k/Downloads/feif/paragon-master/application/main.py", line 12, in <module>
>     from states.transitions.reload_project_transition import ReloadProjectTransition
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
>     return original_import(name, *args, **kwargs)
>   File "/Users/k/Downloads/feif/paragon-master/application/states/transitions/reload_project_transition.py", line 5, in <module>
>     from states.loading_state import LoadingState
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
>     return original_import(name, *args, **kwargs)
>   File "/Users/k/Downloads/feif/paragon-master/application/states/loading_state.py", line 12, in <module>
>     from services.dedicated_editors_service import DedicatedEditorsService
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
>     return original_import(name, *args, **kwargs)
>   File "/Users/k/Downloads/feif/paragon-master/application/services/dedicated_editors_service.py", line 8, in <module>
>     from services.fe14.chapter_service import ChapterService
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
>     return original_import(name, *args, **kwargs)
>   File "/Users/k/Downloads/feif/paragon-master/application/services/fe14/chapter_service.py", line 6, in <module>
>     from model.fe14.chapter_data import ChapterData
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
>     return original_import(name, *args, **kwargs)
>   File "/Users/k/Downloads/feif/paragon-master/application/model/fe14/chapter_data.py", line 23, in <module>
>     CHAPTER_DIALOGUES = _read_dialogue_data()
>   File "/Users/k/Downloads/feif/paragon-master/application/model/fe14/chapter_data.py", line 15, in _read_dialogue_data
>     with open("Modules/ServiceData/FE14ChapterText.json", "r", encoding="utf-8") as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'Modules/ServiceData/FE14ChapterText.json'

Shiboken is annoying me as well; when I tried to compile manually both source instead of using MacOS and a fork, shiboken caused errors so I just run main.py

PS: Solved the text box width issue by switching to Fusion theme (Windows also works)

**Comment by thane98** [comment]
Sorry for the Shiboken issues - those might be a bit tougher for me to troubleshoot as that's part a separate library that Paragon uses (PySide2/Qt). I can try to set up a VM for this in the future, but otherwise I don't have a good way to test outside of Windows and Linux.

I will look into adding a way to toggle the voice lines with the next release - I see how that could be useful.

As for the error that you're getting - I'm not sure if this is related to your changes to the dialogue json since it's failing to find an entirely different file. Possibly an issue of running with the wrong working directory?

**Comment by KSR480** [comment]
Yeah that error is confusing as heck to me, the named file is all fine and idk if Shiboken is just being verbose and actually does its job right

Having placed everything on my user folder I keep getting the same error, oh well I'm glad I can even run this on my Macbook without complications (it is too weak for a VM I'd say, 2013 air model)

**Comment by thane98** [comment]
Well sorry that I don't have a quick fix for that one. I'll see if I can add some extra checks around this with the rewrite so that, in the worst case, the error messages are more informative.
