### ISSUE TITLE
Changing fonts

### ISSUE THREAD

**Issue by KSR480** [thane98/paragon#77]
Hello again,
I'd like to change the Japanese font to Meiryo UI so that it actually is supported by ClearType, but I don't know how I can set Paragon to support it.

**Comment by thane98** [comment]
Paragon doesn't have a way to configure the font currently, but I will add an option for this in the next release.

**Comment by thane98** [comment]
Should be fixed with https://github.com/thane98/paragon/commit/0c5e6321e965b9e4733a62b17c5c6bc246b62bcc

Won't close yet since this hasn't been included in a release build.

**Comment by thane98** [comment]
Release builds here: https://github.com/thane98/paragon/releases/tag/Rewrite-Alpha-1-5

Please reopen if changing the font isn't working or isn't enough to solve the issue for you.
