### ISSUE TITLE
How to import?

### ISSUE THREAD

**Issue by GBOATET** [thane98/paragon#78]
Trying to install a voice mod when it's Readme tells me to just "import the json" that comes with it into Paragon but there's no option at all to do so when my project is already opened.

**Comment by thane98** [comment]
Paragon's currently undergoing a major rewrite. The rewrite does not support import/export yet.

For now, you can use either alpha 14 (https://github.com/thane98/paragon/releases/tag/Alpha-14-3) or alpha 13 (https://github.com/thane98/paragon/releases/tag/Alpha-13-1) to import json patches.
