### ISSUE TITLE
GameData.bin.lz parsing regression from pre-rewrite version of Paragon.

### ISSUE THREAD

**Issue by ImmortalZypther** [thane98/paragon#79]
Got the following error on a GameData.bin.lz that used to work on the pre-rewrite version of Paragon.
I don't know what any of this means or how to "fix" any of it because it works perfectly fine with the older version.
I've uploaded it [here](https://github.com/thane98/paragon/files/6842931/GameData.bin.lz.zip) so you can have a direct look at it. 

```
    0: Failed to read data from store 'gamedata'.
    1: Failed to parse type GameDataFile from file GameData/GameData.bin.lz
    2: Failed to read typename 'GameDataFile' field 'data' at address '0x3344F
    3: Failed to read typename 'GameData' field 'character_table' at address '0x3344F
    4: Failed to read typename 'PersonTable' field 'supports' at address '0x3344F
    5: Failed to read typename 'MainSupportTable' field 'tables' at address '0x3344F
    6: Failed to read typename 'MainSupportTableEntry' field 'table' at address '0x3344F
    7: Failed to read typename 'SupportTable' field 'owner' at address '0x3344F
    8: Unaligned value '209999' should be aligned to 2 bytes.
```

Please add compatibility if possible, thank you very much!

**Comment by thane98** [comment]
Thanks for the report - I have a backlog item to get rid of this validation since it isn't necessary. I will prioritize that for the next release.

**Comment by thane98** [comment]
Solved in an underlying library through https://github.com/thane98/mila/commit/d822f65762273ea6f4b13a34159e70cb302ca663

Will close out once the next release is out.

**Comment by ImmortalZypther** [comment]
Thanks for the fast response! I'll close it if you haven't already when I test the next release.

**Comment by ImmortalZypther** [comment]
Fixed with Rewrite Alpha 2, closing issue.
