### ISSUE TITLE
17+ Skill factor breaks enemy AI [Bug]

### ISSUE THREAD

**Issue by dawnbomb** [thane98/paragon#81]
Seems to happen at random, much more likely with melee locked AI. they break (as in do nothing, permanently) if a skill with more then a factor of 16 exists, and a proc based skill is on them (The proc skill doesn't necessarily need to be the one with a 17 or greater factor either, you can change a unrelated skill, and a default astra will break the AI).

![image](https://user-images.githubusercontent.com/29080681/130497740-673697ad-4044-4e39-b7c7-cd11b5fd2204.png)

this minorly complicated giving skills a 100% proc rate.

**Comment by thane98** [comment]
Can you please explain why you think this is an issue with Paragon and not a game bug?

**Comment by dawnbomb** [comment]
I just assumed that maybe the skill editor was somewhat lazily put together, but i had considered many times it was a bug with the game.

That said, i don't necessarily think game bugs shouldn't be reported either. We can do things like put a hover tool-tip in paragon to let people know.

That said, while i'm basically saying "um... I have no reason, not really anyway", thats not to say i'm not implying things shouldn't change, and i apologize i should have been for clear i had no sleep working all night before i posted.

I suppose it isn't necessarily a bug with paragon, but we could improve paragon by capping multiplying factors at 16.

I'm putting this in github because i don't know how to use github enough to make a branch and pull request, nor to change stuff in paragons FOR a merge request, and i think it would go ignored / whatever in discord chat (probabaly get a "if you think its important do it yourself" and thats fair, but it can still be useful to other people if i post about this and they learn why things are happening, or maybe you will re-read the issues list in a year and fix it when your not busy with other parts of paragon. 

Anyway, it's a thing we *could* improve in paragon, and this is more or less the place we post enhancement / bug or bug-like things, so it seemed appropriate.
