### ISSUE TITLE
Can you use Paragon to merge the Ignis randomizer with the Unit Select Voice?

### ISSUE THREAD

**Issue by MrMostache** [thane98/paragon#84]
Hello,
I don't know much about using Paragon to merge mods. First, I was wondering if your Ignis randomizer is compatible with other mods such as the Unit Select Voice https://gamebanana.com/mods/51423.

If so, how does one go about it?

**Comment by thane98** [comment]
I don't think you need to use Paragon at all to run unit select voice with the randomizer. Use the "romfs" folder from the unit select voice .zip as your output folder in Ignis. That should randomize your game on top of that mod's changes.

**Comment by MrMostache** [comment]
Ah, that sounds like a great idea. I already randomized first, but thankfully I still have the seed number.
