### ISSUE TITLE
Functionality for Locking Skills Missing [FE10]

### ISSUE THREAD

**Issue by Dulnado** [thane98/paragon#85]
Currently, there isn't a way to change a specific part of a skill's data that's required to modify who can equip/unequip a skill. Being able to modify this is required to lock skills entirely or allow specific units/classes to equip them.

For example, for 'Wrath' the bytes for this would be 04 02 00 00 (starts at 33 out of 44 bytes total) and currently you're unable to edit this in Paragon. Removing the skills 'Unlock Item' and conditions may show the locked icon in-game, but you'd still be able to remove it (and if it's a class skill, would crash the game as far as I'm aware).

A field should therefore be added for it.

**Comment by thane98** [comment]
Isn't this covered by the "Learn Conditions" sections on the UI? In the skill module, Paragon has these fields for bytes 33-36:
```
0x33: condition_table_entry_count (1 byte)
0x34: condition_table_2_entry_count (1 byte)
0x35: unknown_2 (2 bytes)
```
followed by the first and second condition table.

This seems to line up with your example for Wrath. Four entries in the first table, two entries in the second table, and unknown_2 is zeroed out. This is what I see in the UI:
![Capture](https://user-images.githubusercontent.com/26237510/152621480-450c7615-26b9-43be-b9e6-02334d30703d.PNG)

Maybe this needs to be renamed from "Learn Conditions" to "Equip Conditions"?

**Comment by Dulnado** [comment]
I've now figured out why this happened. If you click the 'Delete' button to remove all conditions, then the 04 02 00 00 does **not** get cleared (only the 8 bytes after that), resulting in this:

![image](https://user-images.githubusercontent.com/99042461/152621957-b41e4ff2-8a3f-4e6e-b67c-b55877070fd5.png)

Instead, when testing out another skill I deleted each condition _separately_ (next to 'Add') without selecting the aforementioned button at all. That worked as intended.

So it's possibly just a problem with that first option in particular?

**Comment by Dulnado** [comment]
As far as labelling goes, perhaps the **left** conditions should listed as 'Banned Conditions' or 'Cannot be used' with the **right** conditions being the opposite ('Conditions Required'?). I guess that could explain what each table does exactly.

So for Wrath, it cannot be equipped if you _already_ have wrath, or are one of the Herons. And then, so long as that doesn't apply to the unit, they can equip if they're a Beorc or a Laguz.

**Comment by thane98** [comment]
Yeah I think I see what happened here. I'll hide the delete buttons for these tables since there's no reason to use it vs. deleting individual entries.
