### ISSUE TITLE
Cannot install; breaking at maturin

### ISSUE THREAD

**Issue by jenningsconnor** [thane98/paragon#86]
I've followed the directions exactly but am unable to get Paragon off the ground. I keep getting this error:

![image](https://user-images.githubusercontent.com/63885562/158295491-61053d8d-6365-413d-8168-4cff387a77db.png)

Any idea what I'm going wrong?

**Comment by thane98** [comment]
You shouldn't need to build from scratch unless you are trying to modify Paragon's code.

If you just want to install Paragon, have you tried using one of the release builds? [https://github.com/thane98/paragon/releases/tag/Rewrite-Alpha-2-2](https://github.com/thane98/paragon/releases/tag/Rewrite-Alpha-2-2)

**Comment by jenningsconnor** [comment]
Ah, got it; didn't see the link. Thanks!
