### ISSUE TITLE
Fe echoes wont add new spawns

### ISSUE THREAD

**Issue by tyler456780** [thane98/paragon#94]
When i try to add more units to a map in fire emblem echoes, the game doesn't load them or even acknowledge their existence. If i copy paste an extra brigand on chapter 1 the game wont load the brigand.

**Comment by thane98** [comment]
This is an issue with very version of Echoes besides EU. The game loads units at the start of the act, so you need to restart the act to see changes (or use the EU version). There's no way to resolve this through Paragon.
